[[items]]
label = "Showcase"
url = "/"

[[items]]
label = "Concept Homes"
url = "/concept-homes/"

[[items]]
label = "Transformations"
url = "/transformations/"

[[items]]
label = "Properties"
url = "/properties/"

[[items]]
label = "Property Intake"
url = "https://orovianoasis.com"
external = true
