{
  "title": "New Project Name",
  "subtitle": "Interactive property design package",
  "summary": "Write the public project description here.",
  "category": "concept-home",
  "location": "City, State",
  "year": 2026,
  "published": true,
  "featured": false,
  "sort_order": 50,
  "status": "available",
  "status_label": "Available",
  "square_feet": 0,
  "bedrooms": 0,
  "full_bathrooms": 0,
  "half_bathrooms": 0,
  "garage": 0,
  "stories": 0,
  "lot_size": "",
  "price": null,
  "currency": "USD",
  "price_prefix": "",
  "price_suffix": "",
  "price_display_text": "",
  "checkout_url": "",
  "buy_button_label": "Buy Now",
  "contact_button_label": "Request Details",
  "show_contact_with_buy_button": false,
  "carousel_autoplay": true,
  "carousel_interval_ms": 5000,
  "tour_button_label": "Launch 3D Walkthrough",
  "tour_open_new_tab": false,
  "walkthrough": {
    "prefer_dae": false,
    "model_scale": 1,
    "model_offset": [
      0,
      0,
      0
    ],
    "model_rotation_degrees": [
      0,
      0,
      0
    ],
    "entry_position": null,
    "entry_target": null,
    "entry_fov": 70,
    "exterior_position": null,
    "exterior_target": null,
    "exterior_fov": 76,
    "roof_match": [
      "roof",
      "roofing"
    ],
    "slab_match": [
      "slab",
      "floor platform",
      "floor-platform",
      "floor system",
      "upper platform"
    ],
    "collision_exclude": [
      "glass",
      "window",
      "curtain",
      "fixture",
      "furniture",
      "plant",
      "landscape"
    ],
    "eye_height": 1.68,
    "player_radius": 0.28,
    "walk_speed": 3.6,
    "run_speed": 7.2,
    "fly_speed": 6.2,
    "step_height": 0.38,
    "max_drop": 1.2,
    "background": "#8da8b6"
  },
  "product_type": "Digital architectural concept",
  "license_type": "Contact Orovian Oasis for availability",
  "customizable": true,
  "construction_ready": false,
  "property": {
    "listing_type": "",
    "mls_number": "",
    "agent_name": ""
  },
  "transformation": {
    "project_stage": "",
    "property_type": "",
    "duration": "",
    "public_financials": false,
    "acquisition_price": 0,
    "rehab_budget": 0,
    "after_repair_value": 0
  },
  "materials": [],
  "deliverables": []
}
